### ISSUE TITLE
UnboundLocalError: local variable 'user_stats' referenced before assignment

### ISSUE THREAD

**Issue by stukinnear** [ziadhorat/Plex-Spot#1]
Hi there

Installed your app this afternoon.

Got the following error:

UnboundLocalError: local variable 'user_stats' referenced before assignment

Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
File "/app/main.py", line 55, in <module>
    main()
File "/app/main.py", line 27, in main
    active_sessions, _ = get_user_stats(plex_client)
File "/app/app/cache_manager.py", line 7, in wrapper
    return func(*args, **kwargs)
File "/app/app/display.py", line 63, in get_user_stats
    logger.error(f"User stats response: {user_stats}")

My Plex is running on the same Docker instance as plex-spot.

Stu

**Comment by ziadhorat** [comment]
Howzit @stukinnear !

I've quickly pushed and released [v1.0.8 - Added debug logs.](https://github.com/ziadhorat/Plex-Spot/releases/tag/v1.0.8) - latest is also updated.
Are you able to set the environment variable `DEBUG` to True in your `docker-compose.yml` or your `docker run` command and verify if the app is receiving both the url & token correctly via docker logs?

May I also ask if you have more than 1 server linked to your account (and how many libraries are in them)?
I could have very easily overlooked formatting of the api response in many other cases - reason for my Qs.

Thanks for trying it out, glad it could (hopefully) be of use to someone else.

Many a thanks,
Zia

**Comment by stukinnear** [comment]
Hi Zia

Sorry missed your email.

I updated to the latest release and got the same error.

 Error fetching user stats: HTTPConnectionPool(host='localhost',
port=32400): Max retries exceeded with url: /status/sessions (Caused
by NewConnectionError('<urllib3.connection.HTTPConnection object at
0x765afa7e49a0>: Failed to establish a new connection: [Errno 111]
Connection refused'))

2024-09-11 12:50:21.547 Uncaught app exception

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py",
line 88, in exec_func_with_error_handling

    result = func()

  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py",
line 590, in code_to_exec

    exec(code, module.__dict__)

  File "/app/main.py", line 65, in <module>

    main()

  File "/app/main.py", line 39, in main

    col1.metric("Active Streams", user_stats['active_sessions'])

KeyError: 'active_sessions'

2024-09-11 12:50:25,637 - app.display - ERROR - Error fetching user
stats: HTTPConnectionPool(host='localhost', port=32400): Max retries
exceeded with url: /status/sessions (Caused by
NewConnectionError('<urllib3.connection.HTTPConnection object at
0x765afa7c4bb0>: Failed to establish a new connection: [Errno 111]
Connection refused'))

2024-09-11 12:50:25.637 Uncaught app exception

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/exec_code.py",
line 88, in exec_func_with_error_handling

    result = func()

  File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py",
line 590, in code_to_exec

    exec(code, module.__dict__)

  File "/app/main.py", line 65, in <module>

    main()

  File "/app/main.py", line 39, in main

    col1.metric("Active Streams", user_stats['active_sessions'])

KeyError: 'active_sessions'

**Comment by ziadhorat** [comment]
Okay i managed to replicate this issue, both localhost & 127.0.0.1 can't be used to access Plex from Plex-Spot.

I suspect it has something to do with `network_mode: host`, @stukinnear  can I ask you to try the machines local IPv4 address & port `32400` (even though it's on the same machine), I think that should work.

I'll leave this issue open to find a solution for the defaults.

**Comment by stukinnear** [comment]
Thanks for that - it works.
